### ISSUE TITLE
 interledger.org/today is throwing a 404 error

### ISSUE THREAD

**Issue by vineelreddy** [interledger/interledger.org-frontend#12]
[interledger.org/today](http://interledger.org/today) is throwing a 404 error.

**Context:**
/today is shown at the end of https://www.youtube.com/watch?v=pISxxwDcODs and it's a catch-all URL we use to show people what's the most current topic going on with us at any moment. For now, it should redirect to [the specification](https://interledger.org/developers/rfcs/interledger-protocol/). Therefore, it is important we figure out how redirects are done.

**Comment by huijing** [comment]
Closed in favour of https://github.com/interledger/interledger.org-v4/issues/5
